### ISSUE TITLE
Conflitto con la definizione della funzione checkError in Stack/Queue

### ISSUE THREAD

**Issue by fgnm** [taikoiv/Librerie-LASD-2017#1]
Nei sorgenti di Stack e Queue è definita una funzione 
```C
void checkError(int *err) 
``` 
apparentemente inutile, però se provi a compilare sia stack che queue nello stesso eseguibile da giustamente errore perché definita due volte con lo stesso nome. 
Credo che sarebbe il caso di rimuoverla completamente visto che è tutta commentata :)

**Comment by taikoivuni** [comment]
La nuova versione modifica i nomi delle due funzioni. Prova ora ;)
